Antivirus: main.c File Reference
main.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
Enumerations
enum ERROR_GAUSS { SUCCESS = 0 , ERROR_FILE_OPEN = 1 , ERROR_MEMORY_ALLOCATION = 2 , ERROR_FILE_READ = 3 , ERROR_NULL_POINTER = 4 , ERROR_INVALID_INPUT = 5 }
Functions
void print_matrix (double **matrix, size_t rows, size_t cols, FILE *output)
void write_timestamp (FILE *file)
void row_echelon_form (double **matrix, size_t rows, size_t cols)
int main ()
Enumeration Type Documentation
ERROR_GAUSS
enum ERROR_GAUSS
Enumerator
SUCCESS 0
ERROR_FILE_OPEN 1
ERROR_MEMORY_ALLOCATION 2
ERROR_FILE_READ 3
ERROR_NULL_POINTER 4
ERROR_INVALID_INPUT 5
Definition at line 5 of file main.c.
{
    SUCCESS = 0,
    ERROR_FILE_OPEN = 1,
    ERROR_MEMORY_ALLOCATION = 2,
    ERROR_FILE_READ = 3,
    ERROR_NULL_POINTER = 4,
    ERROR_INVALID_INPUT = 5
};
Function Documentation
main()
int main ()
Definition at line 90 of file main.c.
{
    size_t rows, cols;
    int choice;
    printf("Choose input method: 1 - File, 2 - Console\n");
    if (scanf("%d", &choice) != 1)
    {
        perror("Error: Invalid input");
        return ERROR_INVALID_INPUT;
    }
    double **matrix;
    FILE *file;
    if (choice == 1)
    {
        file = fopen("matrix.txt", "r");
        if (file == NULL)
        {
            perror("Error: Unable to open file");
            return ERROR_FILE_OPEN;
        }
        if (fscanf(file, "%zu %zu", &rows, &cols) != 2)
        {
            perror("Error: Failed to read matrix dimensions");
            fclose(file);
            return ERROR_FILE_READ;
        }
        matrix = (double **)malloc(rows * sizeof(double *));
        if (matrix == NULL)
        {
            perror("Error: Memory allocation failed");
            fclose(file);
            return ERROR_MEMORY_ALLOCATION;
        }
        for (size_t i = 0; i < rows; i++)
        {
            matrix[i] = (double *)malloc(cols * sizeof(double));
            if (matrix[i] == NULL)
            {
                perror("Error: Memory allocation failed");
                fclose(file);
                return ERROR_MEMORY_ALLOCATION;
            }
            for (size_t j = 0; j < cols; j++)
            {
                if (fscanf(file, "%lf", &matrix[i][j]) != 1)
                {
                    perror("Error: Failed to read matrix data");
                    fclose(file);
                    return ERROR_FILE_READ;
                }
            }
        }
        fclose(file);
    }
    else if (choice == 2)
    {
        printf("Enter matrix dimensions (rows cols): ");
        if (scanf("%zu %zu", &rows, &cols) != 2)
        {
            perror("Error: Invalid matrix dimensions");
            return ERROR_INVALID_INPUT;
        }
        matrix = (double **)malloc(rows * sizeof(double *));
        if (matrix == NULL)
        {
            perror("Error: Memory allocation failed");
            return ERROR_MEMORY_ALLOCATION;
        }
        for (size_t i = 0; i < rows; i++)
        {
            matrix[i] = (double *)malloc(cols * sizeof(double));
            if (matrix[i] == NULL)
            {
                perror("Error: Memory allocation failed");
                return ERROR_MEMORY_ALLOCATION;
            }
            printf("Enter row %zu: ", i + 1);
            for (size_t j = 0; j < cols; j++)
            {
                if (scanf("%lf", &matrix[i][j]) != 1)
                {
                    perror("Error: Invalid matrix data");
                    return ERROR_INVALID_INPUT;
                }
            }
        }
    }
    else
    {
        perror("Error: Invalid choice");
        return ERROR_INVALID_INPUT;
    }
    FILE *output_file = fopen("matrix.txt", "a");
    if (output_file == NULL)
    {
        perror("Error: Unable to open output file");
        return ERROR_FILE_OPEN;
    }
    write_timestamp(output_file);
    fprintf(output_file, "\nInitial matrix:\n");
    print_matrix(matrix, rows, cols, output_file);
    row_echelon_form(matrix, rows, cols);
    fprintf(output_file, "After Gaussian elimination:\n");
    print_matrix(matrix, rows, cols, output_file);
    fclose(output_file);
    for (size_t i = 0; i < rows; i++)
    {
        free(matrix[i]);
    }
    free(matrix);
    return SUCCESS;
}
References ERROR_FILE_OPEN, ERROR_FILE_READ, ERROR_INVALID_INPUT, ERROR_MEMORY_ALLOCATION, print_matrix(), row_echelon_form(), SUCCESS, and write_timestamp().
print_matrix()
void print_matrix (double ** matrix, size_t rows, size_t cols, FILE * output)
Definition at line 15 of file main.c.
{
    if (matrix == NULL || output == NULL)
    {
        perror("Error: Null matrix or file pointer");
        return;
    }
    for (size_t i = 0; i < rows; i++)
    {
        for (size_t j = 0; j < cols; j++)
        {
            fprintf(output, "%.2f ", matrix[i][j]);
        }
        fprintf(output, "\n");
    }
}
Referenced by main().
row_echelon_form()
void row_echelon_form (double ** matrix, size_t rows, size_t cols)
Definition at line 43 of file main.c.
{
    size_t lead = 0;
    for (size_t r = 0; r < rows; r++)
    {
        if (lead >= cols)
            break;
        size_t i = r;
        while (matrix[i][lead] == 0)
        {
            i++;
            if (i == rows)
            {
                i = r;
                lead++;
                if (lead == cols)
                    return;
            }
        }
        if (i != r)
        {
            double *temp = matrix[i];
            matrix[i] = matrix[r];
            matrix[r] = temp;
        }
        double div = matrix[r][lead];
        for (size_t j = 0; j < cols; j++)
        {
            matrix[r][j] /= div;
        }
        for (size_t i = r + 1; i < rows; i++)
        {
            double factor = matrix[i][lead];
            for (size_t j = lead; j < cols; j++)
            {
                matrix[i][j] -= factor * matrix[r][j];
            }
        }
        lead++;
    }
}
Referenced by main().
write_timestamp()
void write_timestamp (FILE * file)
Definition at line 33 of file main.c.
{
    if (file == NULL)
    {
        perror("Error: Null file pointer");
        return;
    }
    fprintf(file, "\nTimestamp: %s\n", __TIME__);
}
Referenced by main().