Antivirus: antivirus.c File Reference
antivirus.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
Functions
int sum (int a, int b, int *result)
int razn (int a, int b, int *result)
int umn (int a, int b, int *result)
int del (int a, int b, int *result)
int main ()
Function Documentation
del()
int del (int a, int b, int * result)
Definition at line 26 of file отправка/ИсходныйКод/antivirus.c.
{
    if (b == 0) return 2;
    if (result == NULL) return 3;
    *result = a / b;
    return 0;
}
Referenced by main().
main()
int main ()
Definition at line 35 of file отправка/ИсходныйКод/antivirus.c.
{
    int operation;
    int num1, num2;
    int result;
    int func_code;
    if (printf("Vvedite nomer operacii (1-4): \n") < 0)
    {
        printf("Error in function: printf().\nError code: 1");
        return 1;
    }
    if (printf("1. Slozhit\n") < 0)
    {
        printf("Error in function: printf().\nError code: 2");
        return 2;
    }
    if (printf("2. Vychest\n") < 0)
    {
        printf("Error in function: printf().\nError code: 3");
        return 3;
    }
    if (printf("3. Umnozhit\n") < 0)
    {
        printf("Error in function: printf().\nError code: 4");
        return 4;
    }
    if (printf("4. Razdelit (tselochislennoye delenie)\n") < 0)
    {
        printf("Error in function: printf().\nError code: 5");
        return 5;
    }
    if (printf("Vvedite nomer operacii: ") < 0)
    {
        printf("Error in function: printf().\nError code: 6");
        return 6;
    }
    if (scanf("%d", &operation) != 1)
    {
        printf("Error in function: scanf().\nError code: 7");
        return 7;
    }
    if (printf("Vvedite dva chisla: ") < 0)
    {
        printf("Error in function: printf().\nError code: 8");
        return 8;
    }
    if (scanf("%d%d", &num1, &num2) != 2)
    {
        printf("Error in function: scanf().\nError code: 9");
        return 9;
    }
    switch (operation)
    {
        case 1:
            func_code = sum(num1, num2, &result);
            if (func_code != 0)
            {
                printf("Error in function: sum().\nError code: %d\n", func_code);
                return 10;
            }
            if (printf("Rezul'tat: %d + %d = %d\n", num1, num2, result) < 0)
            {
                printf("Error in function: printf().\nError code: 11");
                return 11;
            }
            break;
        case 2:
            func_code = razn(num1, num2, &result);
            if (func_code != 0)
            {
                printf("Error in function: razn().\nError code: %d\n", func_code);
                return 12;
            }
            if (printf("Rezul'tat: %d - %d = %d\n", num1, num2, result) < 0)
            {
                printf("Error in function: printf().\nError code: 13");
                return 13;
            }
            break;
        case 3:
            func_code = umn(num1, num2, &result);
            if (func_code != 0)
            {
                printf("Error in function: umn().\nError code: %d\n", func_code);
                return 14;
            }
            if (printf("Rezul'tat: %d * %d = %d\n", num1, num2, result) < 0)
            {
                printf("Error in function: printf().\nError code: 15");
                return 15;
            }
            break;
        case 4:
            func_code = del(num1, num2, &result);
            if (func_code != 0)
            {
                printf("Error in function: del().\nError code: %d\n", func_code);
                return 16;
            }
            if (printf("Rezul'tat: %d / %d = %d\n", num1, num2, result) < 0)
            {
                printf("Error in function: printf().\nError code: 17");
                return 17;
            }
            break;
        default:
            if (printf("Error in variable: invalid number for operation.\nError code: 18") < 0)
            {
                printf("Error in function: printf().\nError code: 19");
                return 19;
            }
            return 18;
            break;
    }
    return 0;
}
References del(), razn(), sum(), and umn().
razn()
int razn (int a, int b, int * result)
Definition at line 12 of file отправка/ИсходныйКод/antivirus.c.
{
    if (result == NULL) return 3;
    *result = a - b;
    return 0;
}
Referenced by main().
sum()
int sum (int a, int b, int * result)
Definition at line 5 of file отправка/ИсходныйКод/antivirus.c.
{
    if (result == NULL) return 3;
    *result = a + b;
    return 0;
}
Referenced by main().
umn()
int umn (int a, int b, int * result)
Definition at line 19 of file отправка/ИсходныйКод/antivirus.c.
{
    if (result == NULL) return 3;
    *result = a * b;
    return 0;
}
Referenced by main().